version: '3.8'

services:
  postgres_test:
    image: postgres:15-alpine
    container_name: relict_postgres_test
    environment:
      - POSTGRES_USER=test_user
      - POSTGRES_PASSWORD=test_password
      - POSTGRES_DB=test_db
    ports:
      - "5433:5432"
    volumes:
      - ./relict_core/databases/schema.sql:/docker-entrypoint-initdb.d/init.sql

  redis_test:
    image: redis:7-alpine
    container_name: relict_redis_test
    ports:
      - "6380:6379"
