[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "relict-core"
version = "0.1.0"
description = "Event-driven asynchronous framework for proactive AI entities."
authors = [
  { name = "sp.ectr", email = "sp.ectr.raw@gmail.com" }
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pydantic>=2.0",
    "pydantic-settings",
    "redis>=5.0",
    "asyncpg",
    "apscheduler>=4.0.0a1",
    "google-genai",
    "aiogram>=3.0"
]

[tool.setuptools]
packages = [
    "relict_core",
    "relict_core.config",
    "relict_core.databases",
    "relict_core.drivers",
    "relict_core.workers"
]

[tool.setuptools.package-data]
"relict_core.databases" = ["*.sql", "*.schema", "schema.sql"]